[package]
name = "homosexuality-simulator-rust"
version = "0.1.0"
edition = "2021"
authors = ["Jake Walklate <jakewalklate@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"